### ISSUE TITLE
Migrate To-Do/Bug reporting from Trello to GitHub

### ISSUE THREAD

**Issue by TheColorman** [TheColorman/Dunhammer#4]
- [x] Figure out how to use the GitHub API
- [x] Modify Suggestion command to include Label (e.g. "Feature suggest" or "Bug report"), maybe split the command in 2?
- [x] Add GitHub API to Suggestion command
