### ISSUE TITLE
V3 Roadmap

### ISSUE THREAD

**Issue by TheColorman** [TheColorman/Dunhammer#6]
Roadmap for MVP (Minimum Viable Product) for Dunhammer V3.

- [x] General
    - [x] Full implementation of Interactions (slash commands, buttons, select menus, context menus)
    - [x] All settings in 1 command (possibly split into settings/level settings)
    - [x] Setup local MySQL server
- [x] Core commands
    - [x] ping
    - [x] help
    - [x] neko
    - [x] nickname
    - [x] levelupmessage / newrolemessage
- [x] Improved levels
    - [x] New xp system
        - [x] XP streak
        - [x] Bonus xp for longer messages
        - [x] Bonus xp for embeds
        - [x] Global xp system
    - [x] Updated leaderboard
        - [x] Filter by has/doesn't have role
    - [x] Level command
    - [x] Levelup
    - [x] Roles
